CREATE TABLE BLOG(
	BLOG_ID NUMBER PRIMARY KEY,
	BLOG_NAME VARCHAR2(200), 
	BLOG_TITLE VARCHAR2(1000), 
	BLOG_AUTHOR_ID NUMBER	
);

CREATE SEQUENCE SEQ_BLOG;

CREATE TABLE AUTHOR(
	AUTHOR_ID NUMBER PRIMARY KEY,
	AUTHOR_NAME VARCHAR2(200),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);
CREATE SEQUENCE SEQ_AUTHOR;


CREATE TABLE COMM(
	COMM_ID NUMBER PRIMARY KEY,
	COMM_TITLE VARCHAR2(200),
	COMM_CONTENT VARCHAR2(4000),
	BLOG_ID NUMBER,
	FOREIGN KEY (BLOG_ID) REFERENCES BLOG(BLOG_ID)
);

CREATE SEQUENCE SEQ_COMM;

SELECT * FROM BLOG a;
SELECT * FROM AUTHOR b;
SELECT * FROM COMM c;