 CREATE TABLE car(
 sno NUMBER PRIMARY KEY,
 comp VARCHAR2(200)NOT NULL,
 model VARCHAR2(200)NOT NULL,
 cc NUMBER,
 color VARCHAR2(200),
 price NUMBER
 );
 CREATE SEQUENCE SEQ_CAR;
 
SELECT * FROM CAR;     