CREATE TABLE RESTBOARD(
	RBID NUMBER PRIMARY KEY,
    RBWRITER VARCHAR2(200) NOT NULL,
    RBTITLE VARCHAR2(200) NOT NULL,
    RBCONTENT VARCHAR2(4000),
    RBREGDATE TIMESTAMP
);
CREATE SEQUENCE SEQ_RESTBOARD;

DROP TABLE RESTBOARD; 
DROP SEQUENCE SEQ_RESTBOARD;

SELECT * FROM RESTBOARD;