CREATE TABLE USERS (
    USER_ID NUMBER CONSTRAINT USERS_PK PRIMARY KEY,
    USER_NAME VARCHAR2(50) NOT NULL
);

CREATE SEQUENCE USER_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE SCORES (
    USER_ID NUMBER CONSTRAINT SCORES_PK PRIMARY KEY,
    SCORE NUMBER,
    SCORES_O NUMBER,
    SCORES_X NUMBER,
    CONSTRAINT FK_USER_ID FOREIGN KEY (USER_ID) REFERENCES USERS(USER_ID)
);


SELECT * FROM SCORES;
SELECT * FROM USERS;

DROP TABLE USERS;
DROP TABLE SCORES;
DROP SEQUENCE USER_SEQ;