--[SYSTEM 계정접속]

--1.데이터 베이스 생성
--테이블 스페이스명 : GUEST_TABLESPACE
--데이터 파일 : D:/ORACLE/GUEST_TABLESPACE.DBF
			--기본 용량 :100M 기본용량 초과시 10M 증가,최대제하용량 없음]
CREATE TABLESPACE GUEST_TABLESPACE
DATAFILE 'D:\ORACLE\GUEST_TABLESPACE.DBF'
SIZE 100M 
AUTOEXTEND ON NEXT 10M
MAXSIZE UNLIMITED;




--2.사용자 생성
-- ID: GUEST, PW:1234
-- 권한(룰) : CONNECT, RESOURCE
-- 테이블 스페이스 :GUEST_TABLESPACE

CREATE USER GUEST IDENTIFIED BY 1234
DEFAULT TABLESPACE GUEST_TABLESPACE;

GRANT CONNECT, RESOURCE TO GUEST;



--[GUEST 계정접속]

--1. 테이블 생성
-- 테이블명:GUEST
-- 컬럼  : 번호GNO(PK), 이름GNAME(NOT NULL) 나이 GAGE(1~150), 성별GGENDER(M또는 F), 
	--주민 번호GSID(UNIQUE), 접속일지 GCONNDT(NOT NULL)

CREATE TABLE GUEST(
 GNO NUMBER CONSTRAINT G_NO PRIMARY KEY,
 GNAME VARCHAR2(20) CONSTRAINT G_NM NOT NULL,
 GAGE VARCHAR2(3) CONSTRAINT G_AG CHECK (GAGE BETWEEN 1 AND 150), 
 GGENDER CHAR(1) CONSTRAINT G_GE CHECK (GGENDER IN('M','F')),
 GSID VARCHAR2(20) CONSTRAINT G_ID UNIQUE,
 GCONNDT TIMESTAMP  CONSTRAINT G_TI NOT NULL
);



--2. 시퀀스 생성 
--시퀀스명 : SEQ_GUEST(1부터1씩 증가 최대 1000, NOCYCLE, NOCACHE) 
CREATE SEQUENCE SEQ_GUEST
INCREMENT BY 1
START WITH 1
MAXVALUE 1000 
MINVALUE 1
NOCYCLE
NOCACHE;



--[GUEST 테이블]
--임의의 데이터 5건을 입력

INSERT INTO GUEST
VALUES(SEQ_GUEST.NEXTVAL, '홍길동',90, 'M','123456-1234567','2024/01/01');
INSERT INTO GUEST
VALUES(SEQ_GUEST.NEXTVAL, '강감찬',80, 'M','123567-3454567','2024/02/02');
INSERT INTO GUEST
VALUES(SEQ_GUEST.NEXTVAL, '이순신',70, 'M','122356-1254367','2024/03/03');
INSERT INTO GUEST
VALUES(SEQ_GUEST.NEXTVAL, '박지성',40, 'M','124567-1456147','2024/12/11');
INSERT INTO GUEST
VALUES(SEQ_GUEST.NEXTVAL, '김연아',30, 'F','346566-2345467','2024/11/13');

SELECT * FROM GUEST;

--[JDBC 프로그래밍]
--GUEST.JAVA(데이터클래스), GUESTMAIN.JAVA(메인 클래스)
--CONNECTIONUTIL.JAVA(커넥션유틸리티),GUESTDAO.JAVA(CRUD기능 클래스)
--1.패키지: JAVABASIC.JDBC.GUEST
--2.GUESTDAO.JAVA ====>CRUD 기능구현 (LIST,GET,WRITE,UPDATE,DELETE)











