CREATE USER PPP IDENTIFIED BY PPP;
GRANT CONNECT, RESOURCE TO PPP;
DROP USER PPP CASCADE;

-- USERS Table
CREATE TABLE USERS (
    U_NUM NUMBER NOT NULL PRIMARY KEY,
    EMAIL VARCHAR2(200) NOT NULL,
    U_PW VARCHAR2(200) NOT NULL,
    U_PHONE INTEGER NOT NULL,
    U_ID VARCHAR2(50) NOT NULL,
    U_PHOTO VARCHAR2(100) NOT NULL,
    U_DOJ TIMESTAMP NOT NULL,
    U_DOM TIMESTAMP NULL,
    U_ADD VARCHAR2(100) NOT NULL,
    ADMIN CHAR(1) NOT NULL,
    ACTIVATION CHAR(1) NOT NULL
);
ALTER TABLE USERS ADD U_NAME varchar2(20) NOT null; 
-- PET Table
CREATE TABLE PET (
    P_NUM NUMBER NOT NULL PRIMARY KEY,
    P_NAME VARCHAR2(20) NOT NULL,
    P_WEI INTEGER NOT NULL,
    P_HEI INTEGER NOT NULL,
    P_TYPE VARCHAR2(50) NOT NULL,
    P_KIND VARCHAR2(50) NOT NULL,
    P_AGE INTEGER NOT NULL,
    P_PHOTO VARCHAR2(200) NULL,
    P_HS VARCHAR2(50) NOT NULL,
    P_VR VARCHAR2(100) NOT NULL,
    P_GENDER VARCHAR2(3) NOT NULL
);

-- WATCHLIST Table
CREATE TABLE WATCHLIST (
    WL_ID NUMBER NOT NULL PRIMARY KEY,
    U_NUM NUMBER NOT NULL,
    P_NUM NUMBER NOT NULL,
    FOREIGN KEY (U_NUM) REFERENCES USERS(U_NUM),
    FOREIGN KEY (P_NUM) REFERENCES PET(P_NUM)
);

-- BROKERAGE Table
CREATE TABLE BROKERAGE (
    BKG_NUM NUMBER NOT NULL PRIMARY KEY,
    U_NUM NUMBER NOT NULL,
    P_NUM NUMBER NOT NULL,
    TR_NUM NUMBER NOT NULL,
    BKG_SD TIMESTAMP NOT NULL,
    BKG_ED TIMESTAMP NOT NULL,
    BKG_STATUS VARCHAR2(20) NULL,
    BKG_REG TIMESTAMP NULL,
    FOREIGN KEY (U_NUM) REFERENCES USERS(U_NUM),
    FOREIGN KEY (P_NUM) REFERENCES PET(P_NUM)
);

-- CHAT Table
CREATE TABLE CHAT (
    CHAT_ID NUMBER NOT NULL PRIMARY KEY,
    BKG_NUM NUMBER NOT NULL,
    CHAT_SD TIMESTAMP NOT NULL,
    CHAT_ED TIMESTAMP NULL,
    CHAT_STATUS VARCHAR2(20) NULL,
    FOREIGN KEY (BKG_NUM) REFERENCES BROKERAGE(BKG_NUM)
);

-- REVIEW Table
CREATE TABLE REVIEW (
    RV_ID NUMBER NOT NULL PRIMARY KEY,
    BKG_NUM NUMBER NOT NULL,
    RV_SCORE INTEGER NULL,
    RV_TEXT VARCHAR2(200) NULL,
    RV_SD TIMESTAMP NOT NULL,
    RV_MODATE TIMESTAMP NULL,
    FOREIGN KEY (BKG_NUM) REFERENCES BROKERAGE(BKG_NUM)
);

-- REPORT Table
CREATE TABLE REPORT (
    RPT_ID NUMBER NOT NULL PRIMARY KEY,
    RPT_TYPE VARCHAR2(20) NOT NULL,
    RPT_TEXT VARCHAR2(500) NOT NULL,
    RPT_DATE TIMESTAMP NOT NULL,
    RPT_STATUS VARCHAR2(20) NOT NULL,
    U_NUM NUMBER NOT NULL,
    RV_ID NUMBER NULL,
    RPT_IMGS VARCHAR2(100) NULL,
    CHAT_ID NUMBER NULL,
    BKG_NUM NUMBER NULL,
    RPT_IMGO VARCHAR2(100) NULL,
    RPT_COUNT INTEGER NULL,
    FOREIGN KEY (U_NUM) REFERENCES USERS(U_NUM),
    FOREIGN KEY (RV_ID) REFERENCES REVIEW(RV_ID),
    FOREIGN KEY (CHAT_ID) REFERENCES CHAT(CHAT_ID),
    FOREIGN KEY (BKG_NUM) REFERENCES BROKERAGE(BKG_NUM)
);

-- INQUIRY Table
CREATE TABLE INQUIRY (
    INQ_ID NUMBER NOT NULL PRIMARY KEY,
    INQ_TITLE VARCHAR(100) NOT NULL,
    INQ_TEXT VARCHAR2(500) NOT NULL,
    INQ_DATE TIMESTAMP NOT NULL,
    INQ_STATUS VARCHAR2(20) NOT NULL,
    INQ_TYPE VARCHAR2(50) NOT NULL,
    RPT_ID NUMBER NULL,
    BKG_NUM NUMBER NULL,
    RV_ID NUMBER NULL,
    INQ_IMGS VARCHAR2(100) NULL,
    INQ_IMGO VARCHAR2(100) NULL,
    FOREIGN KEY (RPT_ID) REFERENCES REPORT(RPT_ID),
    FOREIGN KEY (BKG_NUM) REFERENCES BROKERAGE(BKG_NUM),
    FOREIGN KEY (RV_ID) REFERENCES REVIEW(RV_ID)
);

-- COMMENTS Table
CREATE TABLE COMMENTS (
    CMT_NUM NUMBER NOT NULL PRIMARY KEY,
    INQ_ID NUMBER NOT NULL,
    CMT_DATE TIMESTAMP NOT NULL,
    CMT_TEXT VARCHAR2(200) NULL,
    FOREIGN KEY (INQ_ID) REFERENCES INQUIRY(INQ_ID)
);

CREATE SEQUENCE USERS_SEQ;
CREATE SEQUENCE PET_SEQ;
CREATE SEQUENCE WATCHLIST_SEQ;
CREATE SEQUENCE BROKERAGE_SEQ;
CREATE SEQUENCE CHAT_SEQ;
CREATE SEQUENCE REVIEW_SEQ;
CREATE SEQUENCE REPORT_SEQ;
CREATE SEQUENCE INQUIRY_SEQ;
CREATE SEQUENCE COMMENTS_SEQ;


SELECT * FROM USERS;
SELECT * FROM PET;
SELECT * FROM WATCHLIST;
SELECT * FROM BROKERAGE;
SELECT * FROM CHAT;
SELECT * FROM REVIEW;
SELECT * FROM REPORT;
SELECT * FROM INQUIRY;
SELECT * FROM COMMENTS;











