CREATE TABLE USERS(
   USERNO INT PRIMARY KEY,
   USERID VARCHAR2(30) NOT NULL,
   NAME VARCHAR2(200) NOT NULL,
   GENDER VARCHAR2(10),
   CITY VARCHAR2(200)
);

CREATE SEQUENCE SEQ_USERS;

DROP  TABLE USERS;


SELECT * FROM USERS;