CREATE TABLE STUDENT(
	SID NUMBER PRIMARY KEY,
	SNAME VARCHAR2(100)NOT NULL,
	SCLASS NUMBER DEFAULT 1,
	SGENDER CHAR(1)CHECK (SGENDER IN('M','F'))
); 

CREATE SEQUENCE STUDENT_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 10000000
NOCYCLE
NOCACHE;


SELECT * FROM STUDENT;


INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생1',1,'M');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생2',2,'F');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생3',3,'M');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생4',4,'F');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생5',5,'M');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생6',6,'F');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '학생7',7,'M');

COMMIT;

SELECT COUNT(*) FROM STUDENT;

ALTER TABLE STUDENT ADD STEL VARCHAR2(20);

SELECT * FROM STUDENT;

ALTER TABLE STUDENT MODIFY STEL VARCHAR2(30);

--ALTER TABLE STUDENT MODIFY SNAME NUMBER;

ALTER TABLE STUDENT DROP COLUMN STEL;

ALTER TABLE STUDENT DROP COLUMN SNAME;

DROP TABLE STUDENT;

DROP SEQUENCE STUDENT_SEQ;

UPDATE STUDENT SET SNAME ='홍길동'
WHERE SID=1;

ROLLBACK;

SELECT * FROM STUDENT;

COMMIT;

DELETE STUDENT
WHERE SID = 7;

SELECT * FROM STUDENT;

ROLLBACK;

CREATE TABLE STUDENT_COPY
AS
SELECT * FROM STUDENT;

SELECT * FROM STUDENT_COPY;

CREATE TABLE STUDENT_COPY_PART
AS
SELECT SNAME, SCLASS FROM STUDENT;

SELECT * FROM STUDENT_COPY_PART;


CREATE TABLE STUDENT_LOW_CLASS
AS
SELECT * FROM STUDENT
WHERE SCLASS<=3;

SELECT * FROM STUDENT_LOW_CLASS;

DROP TABLE STUDENT;

RENAME STUDENT_COPY TO STUDENT;

SELECT * FROM STUDENT;

DROP TABLE STUDENT_COPY_PART;
DROP TABLE STUDENT_LOW_CLASS;
DROP TABLE STUDENT;


SELECT * FROM STUDENT;
SELECT * FROM SUBJECT;



